FROM python:3.8-slim-buster

COPY requirement.txt requirement.txt
RUN pip3 install -r requirement.txt

# COPY ./stock_data.py stock_data.py

# # Add an explicit default behavior for debugging or direct runs
# CMD ["python3"]